analysisChoice: Average
dashboardClientPort: 5558
dashboardPort: 5557
estimateMotion: true
launchDashboard: true
maskFile: /data/u_biswas_software/pyneal-tutorial/Siemens_demo/dummyMask_64-64-18.nii.gz
maskIsWeighted: false
numTimepts: 60
outputPath: /data/pt_02900/rttest
pynealHost: 127.0.0.1
pynealScannerPort: 5557
resultsServerPort: 5555
