analysisChoice: Average
dashboardClientPort: 5550
dashboardPort: 5559
estimateMotion: true
launchDashboard: true
maskFile: /home/meduser/realTimefMRI/workspace/rttest/dummyMask.nii.gz
maskIsWeighted: false
numTimepts: 60
outputPath: /home/meduser/realTimefMRI/raw_data/output
preprocessScript: /home/meduser/realTimefMRI/workspace/nfb/code/pyneal/src/pynealPreprocessing.py
pynealHost: 127.0.0.1
pynealHostIP: 127.0.1.1
pynealScannerPort: 5556
referenceVolume: 0
resultsServerPort: 5555
