analysisChoice: Layers
dashboardClientPort: 5558
dashboardPort: 5557
dicomPath: /data/pt_02900/realtime_export/20240302.27993.cb.27993.cb
estimateMotion: true
launchDashboard: true
layerMaskDeep: /data/hu_biswas/pt2900/pilot/data/sub-cb/proc/roi_layer1_slab.nii
layerMaskMiddle: null
layerMaskSuperior: /data/hu_biswas/pt2900/pilot/data/sub-cb/proc/roi_layer2_slab.nii
maskFile: null
maskIsWeighted: false
numTimepts: 60
numTimeptsUp: 2
numTimeptsDown: 2
outputPath: /data/pt_02900/pilot/data/27993.cb.27993.cb
pynealHost: 127.0.0.1
pynealHostIP: 10.23.10.81
pynealScannerPort: 5556
referenceImage: /data/hu_biswas/pt2900/pilot/data/sub-cb/proc/epi_slab_ref.nii
referenceVolume: None
resultsServerPort: 5555
subjectId: sub-cb
startBlock: down
TR: 2