TR: 2
analysisChoice: Average
dashboardClientPort: 5558
dashboardPort: 5557
dicomPath: /data/pt_02900/realtime_export/20240302.27993.cb.27993.cb
estimateMotion: true
launchDashboard: true
layerMaskDeep: null
layerMaskMiddle: null
layerMaskSuperior: null
maskFile: /data/pt_02900/pilot/data/sub-99/proc/roi_gm_slab.nii
maskIsWeighted: false
numTimepts: 34
numTimeptsDown: 17
numTimeptsUp: 17
outputPath: /data/pt_02900/pilot/data/sub-99
preprocessScript: /data/pt_02900/Neurofeedback/code/preprocessing/pyneal_create_mask.sh
pynealHost: 127.0.0.1
pynealHostIP: 10.0.68.17
pynealScannerPort: 5556
referenceImage: /data/pt_02900/pilot/data/sub-99/proc/epi_slab_ref.nii
referenceVolume: 2
resultsServerPort: 5555
startBlock: down
subjectId: sub-99
