TR: 1
analysisChoice: Average
baseline: 1.0
numVols: 160
numVolsDown: 20
numVolsUp: 20
outputPath: /home/sbiswas/workspace
pynealHostIP: 10.41.60.157
resultsServerPort: 5555
runs: 5
startBlock: down
subjectId: sub-59