analysisChoice: Average
dashboardClientPort: 5558
dashboardPort: 5557
dicomPath: /home/meduser/realTimefMRI/workspace/rttest/pyneal_test2
estimateMotion: true
launchDashboard: false
layerMaskDeep: null
layerMaskMiddle: null
layerMaskSuperior: null
maskFile: /home/meduser/realTimefMRI/workspace/rttest/mask.nii
maskIsWeighted: false
numTimepts: 168
outputPath: /home/meduser/realTimefMRI/workspace/rttest/data
preprocessScript: /home/meduser/realTimefMRI/workspace/real-time_layer/code/pyneal/src/pynealPreprocessing.py
pynealHost: 127.0.0.1
pynealHostIP: 127.0.1.1
pynealScannerPort: 5556
referenceImage: /home/meduser/realTimefMRI/data/20240807.sfassnacht_zyzzyva.24.08.07_10_38_05_DST_1.3.12.2.1107.5.2.0.18951/analysis_s016/s016_bold_mean.nii
referenceVolume: 0
resultsServerPort: 5555
