analysisChoice: Average
dashboardClientPort: 5558
dashboardPort: 5557
dicomPath: /home/meduser/realTimefMRI/workspace/rttest/scannerdata
estimateMotion: true
launchDashboard: true
layerMaskDeep: null
layerMaskMiddle: null
layerMaskSuperior: null
maskFile: /home/meduser/realTimefMRI/workspace/rttest/dummyMask.nii.gz
maskIsWeighted: false
numTimepts: 11
outputPath: /home/meduser/realTimefMRI/workspace/rttest/data
preprocessScript: /home/meduser/realTimefMRI/workspace/nfb/code/preprocessing/pyneal_create_mask.sh
pynealHost: 127.0.0.1
pynealScannerPort: 5556
referenceImage: /home/meduser/realTimefMRI/workspace/rttest/reference.nii.gz
referenceVolume: 2
resultsServerPort: 5555