TR: 3
analysisChoice: Average
dashboardClientPort: 5558
dashboardPort: 5557
dicomPath: /data/pt_02900/realtime_export/20240610.41567.36.41567.36
estimateMotion: true
launchDashboard: true
layerMaskDeep: null
layerMaskMiddle: null
layerMaskSuperior: null
maskFile: /data/pt_02900/pilot/data/sub-59/proc/roi_gm_slab.nii
maskIsWeighted: false
numTimepts: 160
numTimeptsDown: 20
numTimeptsUp: 20
outputPath: /data/pt_02900/pilot/data/sub-59
preprocessScript: /data/pt_02900/Neurofeedback/code/preprocessing/pyneal_create_mask.sh
pynealHost: 127.0.0.1
pynealHostIP: 10.23.10.122
pynealScannerPort: 5556
referenceImage: /data/pt_02900/pilot/data/sub-59/proc/epi_slab_ref.nii
referenceVolume: 2
resultsServerPort: 5555
startBlock: down
subjectId: sub-59
