analysisChoice: Average
dashboardClientPort: 5558
dashboardPort: 5557
dicomPath: /home/meduser/realTimefMRI/workspace
estimateMotion: true
launchDashboard: true
layerMaskDeep: null
layerMaskMiddle: null
layerMaskSuperior: null
maskFile: /home/meduser/realTimefMRI/workspace/
maskIsWeighted: false
numTimepts: 160
outputPath: /home/meduser/realTimefMRI/workspace
preprocessScript: /home/meduser/realTimefMRI/workspace/nfb//code/preprocessing/pyneal_create_mask.sh
pynealHost: 127.0.0.1
pynealScannerSelect: false
dicomDir: /home/meduser/realTimefMRI/workspace/rttest/scannerdata
pynealScannerPort: 5556
referenceImage: /home/meduser/realTimefMRI/workspace/epi_slab_ref.nii
referenceVolume: 2
resultsServerPort: 5555