pynealSocketHost: 127.0.0.1
pynealSocketPort: '5556'
scannerMake: Siemens
scannerSessionDir: /home/meduser/realTimefMRI/workspace/rttest/pyneal_test
outputPath: /home/meduser/realTimefMRI/raw_data/output
